# Bosonic.py

In [1]:
import numpy as np
from scipy.special import binom 
from scipy.sparse import dok_matrix, linalg
from scipy import linalg as linalg_d
from joblib import Memory
import random
import plotly.graph_objects as go
from joblib import Parallel, delayed
from numba import jit, prange
import pickle

location = './cachedir'
memory = Memory(location, verbose=0)

In [ ]:
# Funciones auxiliares optimiadas
@jit
def int_to_tuple(n, b, digits = None):
    r = []
    re = n 
    while re != 0:
        r.append(re%b)
        re = re // b
    if digits is not None:
        if len(r)<digits:
            for i in range(0,digits-len(r)):
                r.append(0)
    r.reverse()
    return r

@jit
def _create_basis(m, d):
    base = []
    index = 0
    for x in range(0,(d+1)**max(d,m)):
        x = int_to_tuple(x,m+1,d)
        if sum(x) == m and len(x) == d:
            base.append(x)
            index += 1
    return base

class fixed_basis:

    # Convierte a un enterno n a su escritura en base b
    def _int_to_tuple(self, n, b, digits = None):
        rep = np.base_repr(n, b)
        rep_int = [int(x,b) for x in rep] 
        if digits is not None:
            zeros = [0 for i in range(0,digits-len(rep))]
            return zeros + rep_int
        else:
            return rep_int
    
    # Revierte la transformacion anterior
    def tuple_to_int(self, t):
        b = self.d-1
        l = len(t)
        s = [t[k]*b**(l-k-1) for k in range(0,l)]
        return sum(s)

    # Convierte el vector en su representacion
    def vect_to_repr(self, vect):
        for i, k in enumerate(vect):
            if k == 1. or k == 1:
                break
        return self.base[i,:]
            
    def rep_to_vect(self, rep):
        rep = list(rep)
        for i, r in [(j, self.base[j,:]) for j in range(0,self.size)]:
            if list(r) == rep:
                return self.canonicals[:,i]
        else:
            None
    
    def rep_to_index(self, rep):
        rep = list(rep)
        for i, r in [(j, self.base[j,:]) for j in range(0,self.size)]:
            if list(r) == rep:
                return i
        else:
            None

    @staticmethod
    def rep_to_exi(rep):
        r = []
        for i, k in enumerate(rep):
            r += [i for x in range(0,k)]
        return r

    # Crea base de M particulas en D estados (repr y base canonica)
    def create_basis(self, m, d):
        length = int(binom(d+m-1,d-1))
        base = np.array(_create_basis(m, d))
        # Asignamos a cada uno de ellos un canónico
        length = int(binom(d+m-1,d-1))
        x = [1.0 for j in range(0,length)]
        canonicals = np.diag(x)
        return base, canonicals
    
    def __init__(self, m, d):
        self.m = m
        self.d = d
        self.size = int(binom(d+m-1,d-1))
        (self.base, self.canonicals) = self.create_basis(m, d)

# Matrices de aniquilación y creación endomórficas. Estan fuera de la clase para poder ser cacheadas        
@memory.cache    
def bdb(basis, i, j):
    mat = dok_matrix((basis.size, basis.size), dtype=np.float32)
    if i != j:
        for k, v in enumerate(basis.base):
            if v[j] != 0:
                dest = list(v.copy())
                dest[j] -= 1
                dest[i] += 1
                tar = basis.rep_to_index(dest)
                mat[tar, k] = np.sqrt(v[i]+1)*np.sqrt(v[j])
    else:
        for k, v in enumerate(basis.base):
            if v[j] != 0:
                mat[k, k] = v[i] 
    return mat

@memory.cache    
def bbd(basis, i, j):
    mat = dok_matrix((basis.size, basis.size), dtype=np.float32)
    if i != j:
        for k, v in enumerate(basis.base):
            if v[i] != 0:
                dest = list(v.copy())
                dest[i] -= 1
                dest[j] += 1
                tar = basis.rep_to_index(dest)
                mat[tar, k] = np.sqrt(v[j]+1)*np.sqrt(v[i])
    else:
        for k, v in enumerate(basis.base):
            mat[k, k] = v[i]+1
    return mat

# Matrices de aniquilación y creación.Toman la base de origen y destino (basis_o, basis_d) resp
@memory.cache   
def b(basis_o, basis_d, i):
    mat = dok_matrix((basis_d.size, basis_o.size), dtype=np.float32)
    for k, v in enumerate(basis_o.base):
        if v[i] != 0:
            dest = list(v.copy())
            dest[i] -= 1   
            tar = basis_d.rep_to_index(dest)
            mat[tar, k] = np.sqrt(v[i])
    return mat


@memory.cache   
def bd(basis_o, basis_d, i):
    mat = dok_matrix((basis_d.size, basis_o.size), dtype=np.float32)
    for k, v in enumerate(basis_o.base):
        dest = list(v.copy())
        dest[i] += 1   
        tar = basis_d.rep_to_index(dest)
        mat[tar, k] = np.sqrt(v[i]+1)
    return mat

# Devuelve la matriz gamma asociada a la descomposición (M,N-M) del vector
@jit
def gamma(basis, m, vect, m_basis = None, nm_basis = None):
    d = basis.d
    if not m_basis or not nm_basis:
        m_basis = fixed_basis(m, d)
        nm_basis = fixed_basis(basis.m-m,d)
    mat = dok_matrix((m_basis.size, nm_basis.size), dtype=np.float32)
    for i, v in enumerate(m_basis.base):
        for j, w in enumerate(nm_basis.base):
            targ = v+w
            index = basis.rep_to_index(targ)
            if index == None:
                continue
            coef = vect[index]
            if coef != 0:      
                aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
                aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
                coef = coef * aux(v) * aux(w) * aux_inv(targ)
                #coef = coef 
                #print(v,w,coef)
            mat[i,j] = coef
    return mat

# Devuelve la matriz rho M asociada al vector
def rho_m(basis, m, vect, m_basis = None, nm_basis = None):
    g = gamma(basis, m, vect, m_basis, nm_basis)
    return np.dot(g,np.transpose(g))

# Devuelve la matriz rho 1 asociada al vector
def rho_1(basis, vect):
    d = basis.d
    mat = dok_matrix((d, d), dtype=np.float32)
    for i in range(0, d):
        for j in range(0, d):
            v = bdb(basis,j,i)*vect
            mat[i,j] = np.inner(vect,v)
    return mat
      
# Devuelve la matriz rho 2 asociada al vector
def rho_2(basis, vect, ml_basis = None, mll_basis = None, t_basis = None):
    d = basis.d
    # Creo las bases si no están dadad
    if ml_basis == None or mll_basis == None or t_basis == None:
        ml_basis = fixed_basis(m-1,d)
        mll_basis = fixed_basis(m-2,d)
        t_basis = fixed_basis(2,d)
    mat = dok_matrix((t_basis.size, t_basis.size), dtype=np.float32)
    for i, v in enumerate(t_basis.base):
        for j, w in enumerate(t_basis.base):
            # Creacion de los a
            i_set = t_basis.rep_to_exi(v)
            b_m = np.dot(b(ml_basis, mll_basis, i_set[1]),b(basis, ml_basis, i_set[0]))
            
            # Creacion de los ad
            i_set = t_basis.rep_to_exi(w)
            bd_m = np.dot(bd(ml_basis, basis, i_set[1]),bd(mll_basis, ml_basis, i_set[0]))    

            # Mult de b's y filleo de mat
            coef = np.inner(vect,np.dot(bd_m,b_m)*vect)
            aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
            mat[i,j] = coef * aux(v) * aux(w)
    return mat    

In [25]:
m = 8
d = 4
import time
ti = time.time()
base = fixed_basis(m, d).base
tf = time.time()
print(tf-ti)
print(base.size)
print(base)

0.06874918937683105
660
[[0 0 0 8]
 [0 0 1 7]
 [0 0 2 6]
 [0 0 3 5]
 [0 0 4 4]
 [0 0 5 3]
 [0 0 6 2]
 [0 0 7 1]
 [0 0 8 0]
 [0 1 0 7]
 [0 1 1 6]
 [0 1 2 5]
 [0 1 3 4]
 [0 1 4 3]
 [0 1 5 2]
 [0 1 6 1]
 [0 1 7 0]
 [0 2 0 6]
 [0 2 1 5]
 [0 2 2 4]
 [0 2 3 3]
 [0 2 4 2]
 [0 2 5 1]
 [0 2 6 0]
 [0 3 0 5]
 [0 3 1 4]
 [0 3 2 3]
 [0 3 3 2]
 [0 3 4 1]
 [0 3 5 0]
 [0 4 0 4]
 [0 4 1 3]
 [0 4 2 2]
 [0 4 3 1]
 [0 4 4 0]
 [0 5 0 3]
 [0 5 1 2]
 [0 5 2 1]
 [0 5 3 0]
 [0 6 0 2]
 [0 6 1 1]
 [0 6 2 0]
 [0 7 0 1]
 [0 7 1 0]
 [0 8 0 0]
 [1 0 0 7]
 [1 0 1 6]
 [1 0 2 5]
 [1 0 3 4]
 [1 0 4 3]
 [1 0 5 2]
 [1 0 6 1]
 [1 0 7 0]
 [1 1 0 6]
 [1 1 1 5]
 [1 1 2 4]
 [1 1 3 3]
 [1 1 4 2]
 [1 1 5 1]
 [1 1 6 0]
 [1 2 0 5]
 [1 2 1 4]
 [1 2 2 3]
 [1 2 3 2]
 [1 2 4 1]
 [1 2 5 0]
 [1 3 0 4]
 [1 3 1 3]
 [1 3 2 2]
 [1 3 3 1]
 [1 3 4 0]
 [1 4 0 3]
 [1 4 1 2]
 [1 4 2 1]
 [1 4 3 0]
 [1 5 0 2]
 [1 5 1 1]
 [1 5 2 0]
 [1 6 0 1]
 [1 6 1 0]
 [1 7 0 0]
 [2 0 0 6]
 [2 0 1 5]
 [2 0 2 4]
 [2 0 3 3]
 [2 0 4 2]
 [2 0 5 1]
 [2 0 6 0]
 [2 1 0 

In [29]:
# Prueba de las matrices gamma (TODO normalizacion)
a = fixed_basis(4, 4)
v = a.rep_to_vect([0, 1, 1, 2])
#+a.rep_to_vect([1, 1, 2, 0])
print(v)
gamma(a, 2, v)
v = np.array([random.random() for a in range(0,a.size)])
v = v / np.linalg.norm(v)
print(v)
gamma(a, 2, v)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 2] [0 1 1 0] 1.0
[0 0 1 1] [0 1 0 1] 1.4142135623730951
[0 1 0 1] [0 0 1 1] 1.4142135623730951
[0 1 1 0] [0 0 0 2] 1.0
[0.00245818 0.12429807 0.09235737 0.05673843 0.05200341 0.23388029
 0.23401698 0.14239911 0.00137916 0.10011861 0.21210931 0.07653313
 0.12088992 0.06257756 0.28254429 0.13310775 0.14610995 0.00906383
 0.06093948 0.15766386 0.15810107 0.10776898 0.11063491 0.14373242
 0.28678535 0.25566518 0.05989708 0.27571683 0.0874394  0.05737582
 0.27334925 0.21140572 0.20371338 0.27734277 0.26057538]
[0 0 0 2] [0 0 0 2] 0.006021284932702713
[0 0 0 2] [0 0 1 1] 0.21529057693064307
[0 0 0 2] [0 0 2 0] 0.09235737145334309
[0 0 0 2] [0 1 0 1] 0.40509254671795236
[0 0 0 2] [0 1 1 0] 0.23401697586066175
[0 0 0 2] [0 2 0 0] 0.10011861433086211
[0 0 0 2] [1 0 0 1] 0.23054938548114984
[0 0 0 2] [1 0 1 0] 0.14610994956373693
[0 0 0 2] [1 1 0 0] 0.15766386006695876
[0 0 0 2] [2 

<10x10 sparse matrix of type '<class 'numpy.float32'>'
	with 100 stored elements in Dictionary Of Keys format>

In [63]:
# Prueba de funcionamiento de las matrices bdb y bbd
v = [1, 1, 0, 2]
vect = a.rep_to_vect(v)
res = bbd(a,0,1) * vect
if np.linalg.norm(res) != 0:
    res = res / np.linalg.norm(res)
    print(a.vect_to_repr(res))
else:
    res = 0
    print(0)


[0 2 0 2]


In [69]:
# Prueba de funcionamiento de las matrices b y bd

l = fixed_basis(3, 3)
m = fixed_basis(2, 3)

vect = l.rep_to_vect([0,1,2])
res = b(l,m,2) * vect
if np.linalg.norm(res) != 0:
    print(res)
    res = res / np.linalg.norm(res)
    print(m.vect_to_repr(res))
    
vect = m.rep_to_vect([0,0,2])
res = bd(m,l,2) * vect
if np.linalg.norm(res) != 0:
    print(res)
    res = res / np.linalg.norm(res)
    print(l.vect_to_repr(res))

[0.         1.41421354 0.         0.         0.         0.        ]
[0 1 1]
[1.73205078 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
[0 0 3]


## Pairing

Construimos el espacio para n particulas en d estados. El hamiltoniano de pairing posee energias equiespaciadas con degeneración doble (asociada a cada estado y su inverso temporal), así como un término de interacción. Por tal motivo, crearemos un espacio con d = 2d.

In [29]:
m = 6
d = 3
# Creo las bases para no tener que recrearlas luego
basis = fixed_basis(m, 2*d)
basis_m1 = fixed_basis(m-1, 2*d)
basis_m2 = fixed_basis(m-2, 2*d)
print(basis.base)
print(basis.size)



[[0 0 0 0 0 6]
 [0 0 0 0 1 5]
 [0 0 0 0 2 4]
 ...
 [5 0 1 0 0 0]
 [5 1 0 0 0 0]
 [6 0 0 0 0 0]]
462


In [27]:
# Parametros hamiltoniano
e = 1
eps = 0.0001
e0 = np.zeros(2*d)
eigenspace_tol = 0.0001
for k in range(0, d):
    r = random.random() * eps
    e0[2*k] = k*e+r
    e0[2*k+1] = k*e+r

def hamiltonian(g, basis, basis_m1, basis_m2):
    # Construccion de H
    h0 = sum([e0[k]*bdb(basis,k,k) for k in range(0,2*d)])
    hi = dok_matrix((basis.size, basis.size), dtype=np.float32)
    for k in range(0,d):
        for kb in range(0,d):
            hi += -1*g*bd(basis_m1, basis, 2*k)*bd(basis_m2, basis_m1, 2*k+1)*b(basis_m1, basis_m2, 2*kb+1)*b(basis, basis_m1, 2*kb)

    return h0+hi

def solve(g, m, last_step = None):
    h = hamiltonian(g, basis, basis_m1, basis_m2)
    sol = linalg.eigsh(h,which='SA',k=19)
    if type(last_step) != type(None):
        # Seleccionamos todos los autovects que difieren sus autovalores menos que tol (mismo autoespacio)
        # y tomamos la proyección en el autoespacio de la solución del paso anterior (last_step)
        eig = sol[0].real
        eigv = sol[1]
        cand = [eigv[:,i].real  for (i, x) in enumerate(eig) if abs(x-min(eig)) < eigenspace_tol]
        cand_norm = [x/np.linalg.norm(x) for x in cand]
        fund = np.zeros(len(cand[0]))
        for x in cand_norm:
            fund += np.dot(last_step,x) * x
        #print(np.dot(fund,last_step))
    else:
        argmin = np.argmin(sol[0].real)
        fund = sol[1][:,argmin]
    fund = fund.real / np.linalg.norm(fund)
    return fund

In [13]:
m = 2
m_basis = fixed_basis(m, 2*d)
nm_basis = fixed_basis(basis.m-m, 2*d)
fund = solve(1, m)
rho = rho_m(basis, m, fund, m_basis, nm_basis).todense()
r = np.sort(linalg_d.eigvals(rho).real)

21

In [31]:
# Rutina de resolución
m = 2
m_basis = fixed_basis(m, 2*d)
nm_basis = fixed_basis(basis.m-m, 2*d)

num = 50
g_range = np.linspace(0.01,5,num)
rho_range= {}

def compute_g(g):
    print(g)
    fund = solve(g, m)
    print('rho')
    rho = rho_m(basis, m, fund, m_basis, nm_basis).todense()
    r = np.sort(linalg_d.eigvals(rho).real)
    rho_range[g] = r

Parallel(n_jobs=8, require='sharedmem')(
    delayed(compute_g)(g) for g in g_range);

0.010.11183673469387755
0.2136734693877551

0.31551020408163266
0.4173469387755102
0.5191836734693878
0.6210204081632653
0.7228571428571429
rho
0.8246938775510204
rho
0.926530612244898
rho
1.0283673469387755
rho
1.130204081632653
rho
1.2320408163265306
rho
1.3338775510204082
rho
1.4357142857142857
rho
1.5375510204081633
rho
1.6393877551020408
rho
1.7412244897959184
rho
1.843061224489796
rho
1.9448979591836735
rho
2.046734693877551
rho
2.1485714285714286
rho
2.250408163265306
rho
2.3522448979591832
rho
2.454081632653061
rho
2.555918367346939
rho
2.657755102040816
rho
2.7595918367346934
rho
2.861428571428571
rho
2.963265306122449
rho
3.0651020408163263
rho
3.1669387755102036
rho
3.2687755102040814
rho
3.370612244897959
rho
3.4724489795918365
rho
3.574285714285714
rho
3.6761224489795916
rho
3.7779591836734694
rho
3.8797959183673467
rho
3.981632653061224
rho
4.083469387755102
rho
4.18530612244898
rho
4.287142857142857
rho
4.388979591836734
rho
4.490816326530612
rho
4.59265306122449
rho
4.6

In [32]:
# Ploteamos
rho_range = dict(sorted(rho_range.items()))
x_axis = list(rho_range.keys())
values = list(rho_range.items())
size = len(values[0][1])
num = 50

fig = go.Figure()
for k in range(0,size):
    fig.add_trace(go.Scatter(
        x=x_axis,
        y=[values[j][1][k] for j in range(0,num)]
    ))
fig.update_layout(xaxis_title=r'$G/\epsilon$',
                   yaxis_title=r'$\lambda^{(1)}$',           
                  showlegend = False,
                     font=dict(
                      size=18,
                   ))
fig.show()

In [14]:
import pickle
with open('rho1p.npy', 'rb') as f:
    rho_range = pickle.load(f)

In [12]:
m = 6
d = 3
# Creo las bases para no tener que recrearlas luego
basis = fixed_basis(m, 2*d)
basis_m1 = fixed_basis(m-1, 2*d)
basis_m2 = fixed_basis(m-2, 2*d)
print(basis.base)
e = 1
eps = 0
e0 = np.zeros(2*d)
for k in range(0, d):
    r = random.random() * eps
    e0[2*k] = k*e+r
    e0[2*k+1] = k*e+r

h = hamiltonian(2, basis, basis_m1, basis_m2)
ha = np.array(h.todense())
ha.astype(np.float32).tofile("myData.dat")
basis.size

[[0 0 0 0 0 6]
 [0 0 0 0 1 5]
 [0 0 0 0 2 4]
 ...
 [5 0 1 0 0 0]
 [5 1 0 0 0 0]
 [6 0 0 0 0 0]]


462

In [23]:
h = hamiltonian(2, basis, basis_m1, basis_m2)
sol = linalg.eigsh(h,which='SA',k=19,return_eigenvectors=True)
eig = sol[0].real
eigv = sol[1]
argmin = np.argmin(sol[0].real)
fund = sol[1][:,argmin]
fund = fund.real / np.linalg.norm(fund)
rho = rho_m(basis, 2, fund).todense()
print(np.sort(linalg_d.eigvals(rho).real))

[0.08498999 0.08499001 0.10967447 0.14576727 0.14576738 0.14576739
 0.1457674  0.24450395 0.24450402 0.40406728 0.40406743 0.40406767
 0.40406787 0.4079797  0.64242506 0.6424253  0.64242554 0.6424258
 1.4782455  1.4782462  6.0978236 ]


In [18]:
rho1 = rho_1(basis, fund).todense()
print(np.trace(rho1))
print(linalg_d.eigvals(rho1).real)

3.9999998
[1.8763163  1.876315   0.12368434 0.12368418]


In [13]:
rho2 = rho_2(basis, fund).todense()
print(np.trace(rho2))
print(linalg_d.eigvals(rho2).real)
np.set_printoptions(suppress=True)


6.0
[0.00731809 3.7699203  0.00731803 0.01199096 0.88363785 0.10904462
 0.88363725 0.10904456 0.10904457 0.10904454]


In [28]:
g = gamma(basis, 2, fund).todense()
rho = np.dot(g,np.transpose(g))
print(np.trace(rho))
fund

0 2
[0 0 0 2] [0 0 2 0] 0.08554583787918091
1 1
[0 0 1 1] [0 0 1 1] 0.17109167575836184
1 8
[0 0 1 1] [1 1 0 0] 0.3302189111709595
2 0
[0 0 2 0] [0 0 0 2] 0.08554583787918091
3 7
[0 1 0 1] [1 0 1 0] 0.3302189111709595
4 6
[0 1 1 0] [1 0 0 1] 0.3302189111709595
5 9
[0 2 0 0] [2 0 0 0] 0.9400199055671692
6 4
[1 0 0 1] [0 1 1 0] 0.3302189111709595
7 3
[1 0 1 0] [0 1 0 1] 0.3302189111709595
8 1
[1 1 0 0] [0 0 1 1] 0.3302189111709595
8 8
[1 1 0 0] [1 1 0 0] 1.8800398111343388
9 5
[2 0 0 0] [0 2 0 0] 0.9400199055671692
6.0000005


array([ 0.00000019, -0.00000003,  0.08554584, -0.00000006,  0.00000006,
        0.00000007, -0.00000002, -0.00000005,  0.00000001, -0.        ,
       -0.00000008,  0.00000001,  0.00000005,  0.00000005, -0.        ,
        0.00000008,  0.00000007, -0.00000007,  0.00000002, -0.00000004,
        0.3302189 ,  0.00000004, -0.00000001, -0.00000015, -0.00000048,
        0.00000002,  0.00000011, -0.00000001,  0.00000016, -0.00000014,
        0.9400199 , -0.00000003,  0.00000011,  0.0000002 , -0.00000003],
      dtype=float32)

In [6]:
m = 6
d = 3
basis = fixed_basis(m, 2*d)
m = 2
m_basis = fixed_basis(m, basis.d)
nm_basis = fixed_basis(basis.m-m, basis.d)

h = hamiltonian(0.01, basis, basis_m1, basis_m2)
sol = linalg.eigsh(h,which='SA',k=19,return_eigenvectors=True)
eig = sol[0].real
eigv = sol[1]
argmin = np.argmin(sol[0].real)
fund = sol[1][:,argmin]
fund = fund.real / np.linalg.norm(fund)
g = gamma(basis, 2, fund).todense()

U, s, Vh = np.linalg.svd(g, full_matrices=False)

parsum = []
for nu in range(0,s.size):
    if nu == 0:
        v = np.zeros(basis.size)
    else:
        v = parsum[nu-1]
    for i, vi in enumerate(m_basis.base):
        for j, wi in enumerate(nm_basis.base):
            targ = vi+wi
            index = basis.rep_to_index(targ)
            aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
            aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
            v += 1/binom(basis.m,m) * np.sqrt(s[nu]) * U[i,nu] * Vh[nu,j] * basis.canonicals[index] * aux(wi) * aux(vi) * aux_inv(targ)
    parsum.append(v/np.linalg.norm(v))
    
for x in range(0,len(parsum)):
    parsum[x] = parsum[x] / np.linalg.norm(parsum[x])

In [7]:
np.linalg.norm(np.dot(np.dot(U,np.diag(s)),Vh)-g)

2.674396e-07

In [23]:
np.linalg.norm(g)

3.8729837

In [11]:
np.dot(fund,parsum[1])

0.9996569142096183

In [11]:
v = np.zeros(basis.size)
for i, vi in enumerate(m_basis.base):
    for j, wi in enumerate(nm_basis.base):
        targ = vi+wi
        index = basis.rep_to_index(targ)
        aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
        aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
        v += 1/binom(basis.m,m) * g[i,j] * basis.canonicals[index] * aux(wi) * aux(vi) * aux_inv(targ)

In [12]:
np.linalg.norm(v/np.linalg.norm(v)-fund)

2.9600115436576405e-08

In [15]:
basis = fixed_basis(4, 4)
m = 2
m_basis = fixed_basis(m, basis.d)
nm_basis = fixed_basis(basis.m-m, basis.d)

v = basis.rep_to_vect([0, 1, 1, 2])+basis.rep_to_vect([1, 1, 2, 0])+basis.rep_to_vect([4,0,0,0])
print(v)
g = gamma(basis, 2, v)
v = np.zeros(basis.size)
for i, vi in enumerate(m_basis.base):
    for j, wi in enumerate(nm_basis.base):
        targ = vi+wi
        index = basis.rep_to_index(targ)
        aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
        aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
        v += 1/binom(basis.m,m) * g[i,j] * basis.canonicals[index] * aux(wi) * aux(vi) * aux_inv(targ)

print(v)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0 0 0 2] [0 1 1 0] 1.0
[0 0 1 1] [0 1 0 1] 1.4142135623730951
[0 0 2 0] [1 1 0 0] 1.0
[0 1 0 1] [0 0 1 1] 1.4142135623730951
[0 1 1 0] [0 0 0 2] 1.0
[0 1 1 0] [1 0 1 0] 1.4142135623730951
[1 0 1 0] [0 1 1 0] 1.4142135623730951
[1 1 0 0] [0 0 2 0] 1.0
[2 0 0 0] [2 0 0 0] 2.4494897427831774
[0.         0.         0.         0.         0.         0.
 0.99999999 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.99999999 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         1.00000004]


In [54]:
nu=0
w = np.zeros(basis.size)
for i, vi in enumerate(m_basis.base):
    for j, wi in enumerate(nm_basis.base):
        targ = vi+wi
        index = basis.rep_to_index(targ)
        aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
        aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
        w += 1/binom(basis.m,m) * np.sqrt(s[nu]) * U[i,nu] * Vh[nu,j] * basis.canonicals[index] * aux(wi) * aux(vi) * aux_inv(targ)
w = w/np.linalg.norm(w)

In [55]:
np.dot(fund,w)

0.9999472732751074

In [66]:
binom(basis.m,m)

15.0

In [13]:
m = 6
d = 3
basis = fixed_basis(m, 2*d)
m = 2
m_basis = fixed_basis(m, basis.d)
nm_basis = fixed_basis(basis.m-m, basis.d)

num = 20
g_range = np.linspace(0.01,5,num)
par_range= {}
overlap_range = {}

for g in g_range:
    h = hamiltonian(g, basis, basis_m1, basis_m2)
    sol = linalg.eigsh(h,which='SA',k=19,return_eigenvectors=True)
    eig = sol[0].real
    eigv = sol[1]
    argmin = np.argmin(sol[0].real)
    fund = sol[1][:,argmin]
    fund = fund.real / np.linalg.norm(fund)
    ga = gamma(basis, 2, fund).todense()

    U, s, Vh = np.linalg.svd(ga, full_matrices=False)

    parsum = []
    for nu in range(0,s.size):
        if nu == 0:
            v = np.zeros(basis.size)
        else:
            v = parsum[nu-1]
        for i, vi in enumerate(m_basis.base):
            for j, wi in enumerate(nm_basis.base):
                targ = vi+wi
                index = basis.rep_to_index(targ)
                aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
                aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
                v += 1/binom(basis.m,m) * np.sqrt(s[nu]) * U[i,nu] * Vh[nu,j] * basis.canonicals[index] * aux(wi) * aux(vi) * aux_inv(targ)
        parsum.append(v / np.linalg.norm(v))

    for x in range(0,len(parsum)):
        parsum[x] = parsum[x] / np.linalg.norm(parsum[x])
        
    par_range[g] = parsum
    overlap_range[g] = [np.abs(np.dot(fund,v)) for v in parsum]

In [20]:
x_axis = list(overlap_range.keys())
values = list(overlap_range.items())
size = len(values[0][1])
num = 20
fig = go.Figure()
for k in range(0,8):
    fig.add_trace(go.Scatter(
        x=x_axis,
        y=[values[j][1][k] for j in range(0,num)]
    ))
fig.update_layout(xaxis_title=r'$G/\epsilon$',
                   yaxis_title='Overlap',           
                  showlegend = False,
                     font=dict(
                      size=18,
                   ))
fig.show()

In [17]:
x_axis = list(overlap_range.keys())
values = list(overlap_range.items())
values

[(0.01,
  [0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314,
   0.9956193411087314]),
 (0.13794871794871796,
  [0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435,
   0.9708364225132435]),

In [70]:
with open('ovlp.npy','wb') as f:
    pickle.dump(overlap_range,f)

In [4]:
with open('ovlp.npy','rb') as f:
    overlap_range = pickle.load(f)