# Bosonic.py

In [2]:
import numpy as np
from scipy.special import binom 
from scipy.sparse import dok_matrix, linalg
from scipy import linalg as linalg_d
from joblib import Memory
import random
import plotly.graph_objects as go
from joblib import Parallel, delayed
from numba import jit, prange

location = './cachedir'
memory = Memory(location, verbose=0)

In [3]:
# Funciones auxiliares optimiadas
@jit
def int_to_tuple(n, b, digits = None):
    r = []
    re = n 
    while re != 0:
        r.append(re%b)
        re = re // b
    if digits is not None:
        if len(r)<digits:
            for i in range(0,digits-len(r)):
                r.append(0)
    r.reverse()
    return r

@jit
def _create_basis(m, d):
    base = []
    index = 0
    for x in range(0,(d+1)**max(d,m)):
        x = int_to_tuple(x,m+1,d)
        if sum(x) == m and len(x) == d:
            base.append(x)
            index += 1
    return base

class fixed_basis:

    # Convierte a un enterno n a su escritura en base b
    def _int_to_tuple(self, n, b, digits = None):
        rep = np.base_repr(n, b)
        rep_int = [int(x,b) for x in rep] 
        if digits is not None:
            zeros = [0 for i in range(0,digits-len(rep))]
            return zeros + rep_int
        else:
            return rep_int
    
    # Revierte la transformacion anterior
    def tuple_to_int(self, t):
        b = self.d-1
        l = len(t)
        s = [t[k]*b**(l-k-1) for k in range(0,l)]
        return sum(s)

    # Convierte el vector en su representacion
    def vect_to_repr(self, vect):
        for i, k in enumerate(vect):
            if k == 1. or k == 1:
                break
        return self.base[i,:]
            
    def rep_to_vect(self, rep):
        rep = list(rep)
        for i, r in [(j, self.base[j,:]) for j in range(0,self.size)]:
            if list(r) == rep:
                return self.canonicals[:,i]
        else:
            None
    
    def rep_to_index(self, rep):
        rep = list(rep)
        for i, r in [(j, self.base[j,:]) for j in range(0,self.size)]:
            if list(r) == rep:
                return i
        else:
            None

    @staticmethod
    def rep_to_exi(rep):
        r = []
        for i, k in enumerate(rep):
            r += [i for x in range(0,k)]
        return r

    # Crea base de M particulas en D estados (repr y base canonica)
    def create_basis(self, m, d):
        length = int(binom(d+m-1,d-1))
        base = np.array(_create_basis(m, d))
        # Asignamos a cada uno de ellos un canónico
        length = int(binom(d+m-1,d-1))
        x = [1.0 for j in range(0,length)]
        canonicals = np.diag(x)
        return base, canonicals
    
    def __init__(self, m, d):
        self.m = m
        self.d = d
        self.size = int(binom(d+m-1,d-1))
        (self.base, self.canonicals) = self.create_basis(m, d)

# Matrices de aniquilación y creación endomórficas. Estan fuera de la clase para poder ser cacheadas        
@memory.cache    
def bdb(basis, i, j):
    mat = dok_matrix((basis.size, basis.size), dtype=np.float32)
    if i != j:
        for k, v in enumerate(basis.base):
            if v[j] != 0:
                dest = list(v.copy())
                dest[j] -= 1
                dest[i] += 1
                tar = basis.rep_to_index(dest)
                mat[tar, k] = np.sqrt(v[i]+1)*np.sqrt(v[j])
    else:
        for k, v in enumerate(basis.base):
            if v[j] != 0:
                mat[k, k] = v[i] 
    return mat

@memory.cache    
def bbd(basis, i, j):
    mat = dok_matrix((basis.size, basis.size), dtype=np.float32)
    if i != j:
        for k, v in enumerate(basis.base):
            if v[i] != 0:
                dest = list(v.copy())
                dest[i] -= 1
                dest[j] += 1
                tar = basis.rep_to_index(dest)
                mat[tar, k] = np.sqrt(v[j]+1)*np.sqrt(v[i])
    else:
        for k, v in enumerate(basis.base):
            mat[k, k] = v[i]+1
    return mat

# Matrices de aniquilación y creación.Toman la base de origen y destino (basis_o, basis_d) resp
@memory.cache   
def b(basis_o, basis_d, i):
    mat = dok_matrix((basis_d.size, basis_o.size), dtype=np.float32)
    for k, v in enumerate(basis_o.base):
        if v[i] != 0:
            dest = list(v.copy())
            dest[i] -= 1   
            tar = basis_d.rep_to_index(dest)
            mat[tar, k] = np.sqrt(v[i])
    return mat


@memory.cache   
def bd(basis_o, basis_d, i):
    mat = dok_matrix((basis_d.size, basis_o.size), dtype=np.float32)
    for k, v in enumerate(basis_o.base):
        dest = list(v.copy())
        dest[i] += 1   
        tar = basis_d.rep_to_index(dest)
        mat[tar, k] = np.sqrt(v[i]+1)
    return mat

# Devuelve la matriz gamma asociada a la descomposición (M,N-M) del vector
def gamma(basis, m, vect, m_basis = None, nm_basis = None):
    d = basis.d
    if not m_basis or not nm_basis:
        m_basis = fixed_basis(m, d)
        nm_basis = fixed_basis(basis.m-m,d)
    mat = dok_matrix((m_basis.size, nm_basis.size), dtype=np.float32)
    for i, v in enumerate(m_basis.base):
        for j, w in enumerate(nm_basis.base):
            targ = v+w
            index = basis.rep_to_index(targ)
            if index == None:
                continue
            coef = vect[index]
            if coef != 0:      
                aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
                aux_inv = lambda x: np.prod(np.sqrt([np.math.factorial(o) for o in x]))
                coef = coef * aux(v) * aux(w) * aux_inv(targ)
            mat[i,j] = coef
    return mat

# Devuelve la matriz rho M asociada al vector
def rho_m(basis, m, vect, m_basis = None, nm_basis = None):
    g = gamma(basis, m, vect, m_basis, nm_basis)
    return np.dot(g,np.transpose(g))

# Devuelve la matriz rho 1 asociada al vector
def rho_1(basis, vect):
    d = basis.d
    mat = dok_matrix((d, d), dtype=np.float32)
    for i in range(0, d):
        for j in range(0, d):
            v = bdb(basis,j,i)*vect
            mat[i,j] = np.inner(vect,v)
    return mat
      
# Devuelve la matriz rho 2 asociada al vector
def rho_2(basis, vect, ml_basis = None, mll_basis = None, t_basis = None):
    d = basis.d
    # Creo las bases si no están dadad
    if ml_basis == None or mll_basis == None or t_basis == None:
        ml_basis = fixed_basis(m-1,d)
        mll_basis = fixed_basis(m-2,d)
        t_basis = fixed_basis(2,d)
    mat = dok_matrix((t_basis.size, t_basis.size), dtype=np.float32)
    for i, v in enumerate(t_basis.base):
        for j, w in enumerate(t_basis.base):
            # Creacion de los a
            i_set = t_basis.rep_to_exi(v)
            b_m = np.dot(b(ml_basis, mll_basis, i_set[1]),b(basis, ml_basis, i_set[0]))
            
            # Creacion de los ad
            i_set = t_basis.rep_to_exi(w)
            bd_m = np.dot(bd(ml_basis, basis, i_set[1]),bd(mll_basis, ml_basis, i_set[0]))    

            # Mult de b's y filleo de mat
            coef = np.inner(vect,np.dot(bd_m,b_m)*vect)
            aux = lambda x: np.prod(np.reciprocal(np.sqrt([np.math.factorial(o) for o in x])))
            mat[i,j] = coef * aux(v) * aux(w)
    return mat    

In [4]:
m = 4
d = 4
import time
ti = time.time()
base = fixed_basis(m, d).base
tf = time.time()
print(tf-ti)
print(base)

0.6876320838928223
[[0 0 0 4]
 [0 0 1 3]
 [0 0 2 2]
 [0 0 3 1]
 [0 0 4 0]
 [0 1 0 3]
 [0 1 1 2]
 [0 1 2 1]
 [0 1 3 0]
 [0 2 0 2]
 [0 2 1 1]
 [0 2 2 0]
 [0 3 0 1]
 [0 3 1 0]
 [0 4 0 0]
 [1 0 0 3]
 [1 0 1 2]
 [1 0 2 1]
 [1 0 3 0]
 [1 1 0 2]
 [1 1 1 1]
 [1 1 2 0]
 [1 2 0 1]
 [1 2 1 0]
 [1 3 0 0]
 [2 0 0 2]
 [2 0 1 1]
 [2 0 2 0]
 [2 1 0 1]
 [2 1 1 0]
 [2 2 0 0]
 [3 0 0 1]
 [3 0 1 0]
 [3 1 0 0]
 [4 0 0 0]]


In [97]:
# Prueba de las matrices gamma (TODO normalizacion)
v = a.rep_to_vect([0, 1, 1, 2])+a.rep_to_vect([1, 1, 2, 0])
print(v)
gamma(a, 2, v)
v = np.array([random.random() for a in range(0,a.size)])
v = v / np.linalg.norm(v)
print(v)
gamma(a, 2, v)

AttributeError: 'tuple' object has no attribute 'rep_to_vect'

In [63]:
# Prueba de funcionamiento de las matrices bdb y bbd
v = [1, 1, 0, 2]
vect = a.rep_to_vect(v)
res = bbd(a,0,1) * vect
if np.linalg.norm(res) != 0:
    res = res / np.linalg.norm(res)
    print(a.vect_to_repr(res))
else:
    res = 0
    print(0)


[0 2 0 2]


In [69]:
# Prueba de funcionamiento de las matrices b y bd

l = fixed_basis(3, 3)
m = fixed_basis(2, 3)

vect = l.rep_to_vect([0,1,2])
res = b(l,m,2) * vect
if np.linalg.norm(res) != 0:
    print(res)
    res = res / np.linalg.norm(res)
    print(m.vect_to_repr(res))
    
vect = m.rep_to_vect([0,0,2])
res = bd(m,l,2) * vect
if np.linalg.norm(res) != 0:
    print(res)
    res = res / np.linalg.norm(res)
    print(l.vect_to_repr(res))

[0.         1.41421354 0.         0.         0.         0.        ]
[0 1 1]
[1.73205078 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
[0 0 3]


## Pairing

Construimos el espacio para n particulas en d estados. El hamiltoniano de pairing posee energias equiespaciadas con degeneración doble (asociada a cada estado y su inverso temporal), así como un término de interacción. Por tal motivo, crearemos un espacio con d = 2d.

In [8]:
m = 4
d = 3
# Creo las bases para no tener que recrearlas luego
basis = fixed_basis(m, 2*d)
basis_m1 = fixed_basis(m-1, 2*d)
basis_m2 = fixed_basis(m-2, 2*d)
print(basis.base)
print(basis.size)



[[0 0 0 0 0 4]
 [0 0 0 0 1 3]
 [0 0 0 0 2 2]
 [0 0 0 0 3 1]
 [0 0 0 0 4 0]
 [0 0 0 1 0 3]
 [0 0 0 1 1 2]
 [0 0 0 1 2 1]
 [0 0 0 1 3 0]
 [0 0 0 2 0 2]
 [0 0 0 2 1 1]
 [0 0 0 2 2 0]
 [0 0 0 3 0 1]
 [0 0 0 3 1 0]
 [0 0 0 4 0 0]
 [0 0 1 0 0 3]
 [0 0 1 0 1 2]
 [0 0 1 0 2 1]
 [0 0 1 0 3 0]
 [0 0 1 1 0 2]
 [0 0 1 1 1 1]
 [0 0 1 1 2 0]
 [0 0 1 2 0 1]
 [0 0 1 2 1 0]
 [0 0 1 3 0 0]
 [0 0 2 0 0 2]
 [0 0 2 0 1 1]
 [0 0 2 0 2 0]
 [0 0 2 1 0 1]
 [0 0 2 1 1 0]
 [0 0 2 2 0 0]
 [0 0 3 0 0 1]
 [0 0 3 0 1 0]
 [0 0 3 1 0 0]
 [0 0 4 0 0 0]
 [0 1 0 0 0 3]
 [0 1 0 0 1 2]
 [0 1 0 0 2 1]
 [0 1 0 0 3 0]
 [0 1 0 1 0 2]
 [0 1 0 1 1 1]
 [0 1 0 1 2 0]
 [0 1 0 2 0 1]
 [0 1 0 2 1 0]
 [0 1 0 3 0 0]
 [0 1 1 0 0 2]
 [0 1 1 0 1 1]
 [0 1 1 0 2 0]
 [0 1 1 1 0 1]
 [0 1 1 1 1 0]
 [0 1 1 2 0 0]
 [0 1 2 0 0 1]
 [0 1 2 0 1 0]
 [0 1 2 1 0 0]
 [0 1 3 0 0 0]
 [0 2 0 0 0 2]
 [0 2 0 0 1 1]
 [0 2 0 0 2 0]
 [0 2 0 1 0 1]
 [0 2 0 1 1 0]
 [0 2 0 2 0 0]
 [0 2 1 0 0 1]
 [0 2 1 0 1 0]
 [0 2 1 1 0 0]
 [0 2 2 0 0 0]
 [0 3 0 0 0 1]
 [0 3 0 0 

In [9]:
# Parametros hamiltoniano
e = 1
eps = 0.0001
e0 = np.zeros(2*d)
eigenspace_tol = 0.0001
for k in range(0, d):
    r = random.random() * eps
    e0[2*k] = k*e+r
    e0[2*k+1] = k*e+r

def hamiltonian(g, basis, basis_m1, basis_m2):
    # Construccion de H
    h0 = sum([e0[k]*bdb(basis,k,k) for k in range(0,2*d)])
    hi = dok_matrix((basis.size, basis.size), dtype=np.float32)
    for k in range(0,d):
        for kb in range(0,d):
            hi += -1*g*bd(basis_m1, basis, 2*k)*bd(basis_m2, basis_m1, 2*k+1)*b(basis_m1, basis_m2, 2*kb+1)*b(basis, basis_m1, 2*kb)

    return h0+hi

def solve(g, m, last_step = None):
    h = hamiltonian(g, basis, basis_m1, basis_m2)
    sol = linalg.eigsh(h,which='SA',k=19)
    if type(last_step) != type(None):
        # Seleccionamos todos los autovects que difieren sus autovalores menos que tol (mismo autoespacio)
        # y tomamos la proyección en el autoespacio de la solución del paso anterior (last_step)
        eig = sol[0].real
        eigv = sol[1]
        cand = [eigv[:,i].real  for (i, x) in enumerate(eig) if abs(x-min(eig)) < eigenspace_tol]
        cand_norm = [x/np.linalg.norm(x) for x in cand]
        fund = np.zeros(len(cand[0]))
        for x in cand_norm:
            fund += np.dot(last_step,x) * x
        #print(np.dot(fund,last_step))
    else:
        argmin = np.argmin(sol[0].real)
        fund = sol[1][:,argmin]
    fund = fund.real / np.linalg.norm(fund)
    return fund

In [7]:
# Rutina de resolución
m = 1
m_basis = fixed_basis(m, 2*d)
nm_basis = fixed_basis(basis.m-m, 2*d)

num = 100
g_range = np.linspace(0.01,5,num)
rho_range= {}

def compute_g(g):
    print(g)
    fund = solve(g, m)
    rho = rho_m(basis, m, fund, m_basis, nm_basis).todense()
    r = np.sort(linalg_d.eigvals(rho).real)
    rho_range[g] = r

Parallel(n_jobs=8, require='sharedmem')(
    delayed(compute_g)(g) for g in g_range);

0.01
0.060404040404040410.11080808080808081

0.16121212121212125
0.21161616161616165
0.26202020202020204
0.3124242424242425
0.3628282828282829
0.4132323232323233
0.4636363636363637
0.5140404040404041
0.5644444444444445
0.614848484848485
0.6652525252525253
0.7156565656565658
0.7660606060606061
0.81646464646464660.8668686868686870.9172727272727274


0.9676767676767678
1.0180808080808081
1.0684848484848486
1.118888888888889
1.1692929292929295
1.21969696969697
1.2701010101010102
1.3205050505050506
1.370909090909091
1.4213131313131315
1.471717171717172
1.5221212121212122
1.5725252525252527
1.622929292929293
1.6733333333333336
1.723737373737374
1.7741414141414142
1.8245454545454547
1.8749494949494951
1.92535353535353561.975757575757576

2.026161616161616
2.0765656565656565
2.126969696969697
2.1773737373737374
2.227777777777778
2.2781818181818183
2.3285858585858588
2.378989898989899
2.4293939393939397
2.4797979797979797
2.53020202020202
2.5806060606060606
2.631010101010101
2.6814141414141415


In [178]:
# Ploteamos
rho_range = dict(sorted(rho_range.items()))
x_axis = list(rho_range.keys())
values = list(rho_range.items())
size = len(values[0][1])

fig = go.Figure()
for k in range(0,size):
    fig.add_trace(go.Scatter(
        x=x_axis,
        y=[values[j][1][k] for j in range(0,num)]
    ))
fig.update_layout(xaxis_title='G',
                   yaxis_title='Rho2')
fig.show()

In [11]:
m = 4
d = 4
# Creo las bases para no tener que recrearlas luego
basis = fixed_basis(m, 2*d)
basis_m1 = fixed_basis(m-1, 2*d)
basis_m2 = fixed_basis(m-2, 2*d)
print(basis.base)
e = 1
eps = 0
e0 = np.zeros(2*d)
for k in range(0, d):
    r = random.random() * eps
    e0[2*k] = k*e+r
    e0[2*k+1] = k*e+r

h = hamiltonian(2, basis, basis_m1, basis_m2)
ha = np.array(h.todense())
ha.astype(np.float32).tofile("myData.dat")
basis.size

[[0 0 0 ... 0 0 4]
 [0 0 0 ... 0 1 3]
 [0 0 0 ... 0 2 2]
 ...
 [3 0 1 ... 0 0 0]
 [3 1 0 ... 0 0 0]
 [4 0 0 ... 0 0 0]]


330

In [14]:
h = hamiltonian(1000000, basis, basis_m1, basis_m2)
sol = linalg.eigsh(h,which='SA',k=19,return_eigenvectors=True)
eig = sol[0].real
eigv = sol[1]
argmin = np.argmin(sol[0].real)
fund = sol[1][:,argmin]
fund = fund.real / np.linalg.norm(fund)
rho = rho_m(basis, 2, fund).todense()
print(linalg_d.eigvals(rho).real)
eig


[0.0999997  0.10000002 2.5000002  0.10000013 0.10000028 0.10000008
 0.09999993 0.0999997  0.09999981 0.09999999 0.09999975 0.09999979
 0.09999982 0.09999996 0.10000022 0.10000026 0.1000001  0.10000025
 0.09999979 0.0999999  0.0999999  0.10000021 0.10000017 0.09999994
 0.10000004 0.1000001  0.09999993 0.09999997 0.10000015 0.10000023
 0.10000017 0.09999999 0.10000005 0.10000003 0.09999999 0.10000005]


array([-9999993.72617466, -5999997.89231149, -5999997.89231145,
       -5999996.70759559, -5999996.52975324, -5999996.52975324,
       -5999996.52975323, -5999996.52975322, -5999995.22564455,
       -5999995.22564454, -5999995.19641999, -5999995.19641997,
       -5999995.19641996, -5999995.19641995, -5999993.8630869 ,
       -5999993.8630869 , -5999993.86308689, -5999993.86308645,
       -5999993.86308645])

In [18]:
rho1 = rho_1(basis, fund).todense()
print(np.trace(rho1))
print(linalg_d.eigvals(rho1).real)

3.9999998
[1.8763163  1.876315   0.12368434 0.12368418]


In [13]:
rho2 = rho_2(basis, fund).todense()
print(np.trace(rho2))
print(linalg_d.eigvals(rho2).real)
np.set_printoptions(suppress=True)


6.0
[0.00731809 3.7699203  0.00731803 0.01199096 0.88363785 0.10904462
 0.88363725 0.10904456 0.10904457 0.10904454]


In [28]:
g = gamma(basis, 2, fund).todense()
rho = np.dot(g,np.transpose(g))
print(np.trace(rho))
fund

0 2
[0 0 0 2] [0 0 2 0] 0.08554583787918091
1 1
[0 0 1 1] [0 0 1 1] 0.17109167575836184
1 8
[0 0 1 1] [1 1 0 0] 0.3302189111709595
2 0
[0 0 2 0] [0 0 0 2] 0.08554583787918091
3 7
[0 1 0 1] [1 0 1 0] 0.3302189111709595
4 6
[0 1 1 0] [1 0 0 1] 0.3302189111709595
5 9
[0 2 0 0] [2 0 0 0] 0.9400199055671692
6 4
[1 0 0 1] [0 1 1 0] 0.3302189111709595
7 3
[1 0 1 0] [0 1 0 1] 0.3302189111709595
8 1
[1 1 0 0] [0 0 1 1] 0.3302189111709595
8 8
[1 1 0 0] [1 1 0 0] 1.8800398111343388
9 5
[2 0 0 0] [0 2 0 0] 0.9400199055671692
6.0000005


array([ 0.00000019, -0.00000003,  0.08554584, -0.00000006,  0.00000006,
        0.00000007, -0.00000002, -0.00000005,  0.00000001, -0.        ,
       -0.00000008,  0.00000001,  0.00000005,  0.00000005, -0.        ,
        0.00000008,  0.00000007, -0.00000007,  0.00000002, -0.00000004,
        0.3302189 ,  0.00000004, -0.00000001, -0.00000015, -0.00000048,
        0.00000002,  0.00000011, -0.00000001,  0.00000016, -0.00000014,
        0.9400199 , -0.00000003,  0.00000011,  0.0000002 , -0.00000003],
      dtype=float32)

In [8]:
import time
t = time.time()
r1 = rho_m(basis, 2, fund)
to = time.time()
print(to-t)
t = time.time()
r1 = rho_2(basis, fund)
to = time.time()
print(to-t)

0.030218124389648438
0.31302523612976074
